---
- name: Download file
  get_url:
    url: '{{ influx_deb_url }}'
    dest: ~/influxdb.deb
    force_basic_auth: yes

- name: Install InfluxDB from deb package
  apt:
    deb: ~/influxdb.deb
    state: present
  become: yes

- name: Copy influxdb.conf
  template:
    src: templates/influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
    owner: root
    group: root
  notify:
    - restart influxdb
  become: yes

- name: Create DB
  shell: |
    influxdb -execute 'CREATE USER {{ influx.admin_username }} WITH PASSWORD {{ admin_password }} WITH ALL PRIVILEGES'
    influxdb -execute 'CREATE DATABASE {{ influx.database_name }}'
  become: yes
